typescript;
/// <reference types="astro/client" />

// Import the Env interface from the file generated by 'wrangler types'
type Env = import("../worker-configuration").Env;

declare namespace App {
  interface Locals {
    runtime: {
      env: Env;
      cf: import("@cloudflare/workers-types").IncomingRequestCfProperties;
      ctx: import("@cloudflare/workers-types").ExecutionContext;
    };
  }
}

export {};
